package com.apocalyptolabs.viking.core.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import com.apocalyptolabs.viking.core.model.ThreatResult

object CybercrimeReportExporter {

    fun dial1930Helpline(context: Context) {
        try {
            val intent = Intent(Intent.ACTION_DIAL).apply {
                data = Uri.parse("tel:1930")
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    fun formatIncidentReportText(threat: ThreatResult): String {
        return """
            NATIONAL CYBERCRIME HELPLINE (1930) INCIDENT EVIDENCE PACKET
            -------------------------------------------------------------
            Generated by VIKING On-Device AI Security Agent
            
            Incident Timestamp : ${threat.timestamp.toFormattedDate()}
            Threat Category    : ${threat.type.name}
            Severity Level     : ${threat.severity.name}
            Target Entity      : ${threat.target}
            Evidence Summary   : ${threat.explanation}
            Recommended Action : ${threat.action}
            
            Note: Submit this evidence log at https://cybercrime.gov.in within the 1-hour golden period.
        """.trimIndent()
    }
}
